# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Chris Hansen's Nut Shack
subtitle: Have a seat, right over there.
description: A place for random garbage.
author: chrishansen69 (rafa1231518)
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://rafa1231518.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: # https://github.com/hexojs/hexo/issues/1591
#  - "**.js" #nope
#  - "**.css" #nope
#  - "*.js" #nope
#  - "libraries/lib/codemirror.js" #yep
  - "libraries/lib/*" #yep
  - "libraries/mode/*/*"
  - "libraries/mode/rpm/changes/index.html"
  - "libraries/uglify.js"
  - "libraries/_uglify.js"
  - "libraries/beautify.js"
  - "libraries/jshint.js"
  - "libraries/*"
  - "ss64/main.css"
  - "ss64/opensearchdescription.xml"
  - "ss64/robots.txt"
  - "ss64/rss.xml"
  - "ss64/tables.css"
  - "ss64/access/abs.png"
  - "ss64/access/asc.png"
  - "ss64/access/ascw.png"
  - "ss64/access/avg.png"
  - "ss64/access/chr.png"
  - "ss64/access/count.png"
  - "ss64/access/date.png"
  - "ss64/access/dateadd.png"
  - "ss64/access/datediff.png"
  - "ss64/access/datepart.png"
  - "ss64/access/dateserial.png"
  - "ss64/access/davg.png"
  - "ss64/access/day.png"
  - "ss64/access/dcount.png"
  - "ss64/access/default-properties.jpg"
  - "ss64/access/dfirst.png"
  - "ss64/access/dlast.png"
  - "ss64/access/dlookup.png"
  - "ss64/access/dmax.png"
  - "ss64/access/dmin.png"
  - "ss64/access/dsum.png"
  - "ss64/access/exp.png"
  - "ss64/access/first-last.png"
  - "ss64/access/fix.png"
  - "ss64/access/hex.png"
  - "ss64/access/hour.png"
  - "ss64/access/isnull.png"
  - "ss64/access/null.png"
  - "ss64/access/nz.png"
  - "ss64/access/query.png"
  - "ss64/css/boxmodel.png"
  - "ss64/css/sorttable.js"
  - "ss64/css/try.js"
  - "ss64/docs/icons.zip"
  - "ss64/docs/ccimages/by.png"
  - "ss64/docs/ccimages/nc.png"
  - "ss64/docs/ccimages/remix.png"
  - "ss64/docs/ccimages/sa.png"
  - "ss64/docs/ccimages/share.png"
  - "ss64/images/flag.png"
  - "ss64/images/mode2.jpg"
  - "ss64/images/smile.jpg"
  - "ss64/images/sorttable.js"
  - "ss64/images/top.png"
  - "ss64/links/access-cook.jpg"
  - "ss64/links/accessgetz2000.jpg"
  - "ss64/links/acid.jpg"
  - "ss64/links/adminpaksp1.txt"
  - "ss64/links/adminpaksp2.txt"
  - "ss64/links/bash-kier-ubuntu.jpg"
  - "ss64/links/bash_cookbook.jpg"
  - "ss64/links/css-html.jpg"
  - "ss64/links/css-mastery.jpg"
  - "ss64/links/gennick_loader.jpg"
  - "ss64/links/linuxnutshell.gif"
  - "ss64/links/nix_essential.jpg"
  - "ss64/links/ora-essentials.jpg"
  - "ss64/links/ora-lewis.jpg"
  - "ss64/links/ora-perform.jpg"
  - "ss64/links/ora-simply.jpg"
  - "ss64/links/ora_kyte_eff.jpg"
  - "ss64/links/ora_sqlcook.jpg"
  - "ss64/links/osx_bash.jpg"
  - "ss64/links/osx_ml.jpg"
  - "ss64/links/osx_snow_missing.jpg"
  - "ss64/links/osx_support.jpg"
  - "ss64/links/osx_ugeeks.jpg"
  - "ss64/links/payette.jpg"
  - "ss64/links/pslunches.jpg"
  - "ss64/links/ps_cookbook.jpg"
  - "ss64/links/resource-kit-2003.txt"
  - "ss64/links/sql2008.jpg"
  - "ss64/links/sql2012.jpg"
  - "ss64/links/sql_delaney.jpg"
  - "ss64/links/tsql05.jpg"
  - "ss64/links/unixpowertools.jpg"
  - "ss64/links/unixsysadmin.jpg"
  - "ss64/links/vbsreference.jpg"
  - "ss64/links/win08reskit.jpg"
  - "ss64/links/win7reskit.jpg"
  - "ss64/links/winsysinternals.jpg"
  - "ss64/links/win_batchography.jpg"
  - "ss64/links/win_internals.jpg"
  - "ss64/links/win_knittel.jpg"
  - "ss64/links/win_minasi.jpg"
  - "ss64/links/win_pogue.jpg"
  - "ss64/links/wsh_borge2.jpg"
  - "ss64/links/wsh_nutshell.jpg"
  - "ss64/links/wsh_scripting.jpg"
  - "ss64/links/xp-support-tools.txt"
  - "ss64/nt/adprintx.zip"
  - "ss64/nt/bigtext.cmd.txt"
  - "ss64/nt/color.gif"
  - "ss64/nt/datemath.txt"
  - "ss64/nt/delolder.txt"
  - "ss64/nt/dpi-default-96.txt"
  - "ss64/nt/dpi-large-144.txt"
  - "ss64/nt/dpi-medium-120.txt"
  - "ss64/nt/dpi-small-96.txt"
  - "ss64/nt/DrvReady.txt"
  - "ss64/nt/elevate.png"
  - "ss64/nt/fassoc.txt"
  - "ss64/nt/icacls.png"
  - "ss64/nt/installed.txt"
  - "ss64/nt/rdp.png"
  - "ss64/nt/services.jpg"
  - "ss64/nt/shared.png"
  - "ss64/nt/spack.txt"
  - "ss64/nt/syntax-admins.jpg"
  - "ss64/nt/syntax-groupnesting.jpg"
  - "ss64/nt/syntax-groups-nested.jpg"
  - "ss64/nt/syntax-groups.jpg"
  - "ss64/nt/uac.jpg"
  - "ss64/nt/whereami.txt"
  - "ss64/office/apportionment.xls"
  - "ss64/office/benfordslaw.xls"
  - "ss64/office/calendar.dot"
  - "ss64/office/calendar.xls"
  - "ss64/office/calendar.xlsx"
  - "ss64/office/calendarfy.xls"
  - "ss64/office/calendarfy.xlsx"
  - "ss64/office/charts.zip"
  - "ss64/office/lottery.xls"
  - "ss64/office/procedures.dot"
  - "ss64/office/ProjectPlanGantt.zip"
  - "ss64/office/shifts.xls"
  - "ss64/ora/connectby.sql.txt"
  - "ss64/ora/oracle_11g_architecture.jpg"
  - "ss64/ora/syntax-architecture.ppt"
  - "ss64/ora/syntax-exp.txt"
  - "ss64/ora/syntax-Imp.txt"
  - "ss64/ora/syntax-sqlload.txt"
  - "ss64/ora/syntax-sqlplus-set-commands.txt"
  - "ss64/ora/syntax-tnsnames.jpg"
  - "ss64/ora/syntax-tnsnames1.jpg"
  - "ss64/ora/syntax-tnsnames2.jpg"
  - "ss64/ora/syntax-tnsnamesdbca.jpg"
  - "ss64/osx/command-key.gif"
  - "ss64/osx/defaults-show-hidden_scpt.txt"
  - "ss64/osx/key_br.gif"
  - "ss64/osx/key_dn.gif"
  - "ss64/osx/key_tl.gif"
  - "ss64/osx/key_up.gif"
  - "ss64/osx/option-key.gif"
  - "ss64/osx/shift-key.gif"
  - "ss64/osx/ytdl.jpg"
  - "ss64/pass/passwords.zip"
  - "ss64/pass/strongpw.zip"
  - "ss64/pass/iphone/apple-touch-icon.png"
  - "ss64/pass/mobile/icon.png"
  - "ss64/pass/mobile/css/bootstrap.min.css"
  - "ss64/pass/mobile/css/custom.css"
  - "ss64/ps/bits.txt"
  - "ss64/ps/EchoArgs.exe"
  - "ss64/ps/zip.txt"
  - "ss64/sql/dimtimes_create_table.txt"

#{{
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cyanstyle

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: github
  repository: https://github.com/rafa1231518/rafa1231518.github.io.git
  branch: master

# Marked config
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true # Doesn't escape HTML content
    xhtmlOut: false # Parser will not produce XHTML compliant code. Ex: A line break will be <br>
    breaks: true # Parser produces `<br>` tags every time there is a line break in the source document.
    linkify: true # Returns text links as proper links inlined with the paragraph.
    typographer: true # Substitution of common typographical elements will take place.
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

# Hexo-all-minifier 
## Docs: https://github.com/unhealthy/hexo-all-minifier
html_minifier:
  enable: true
  exclude: 

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false